-- ============================================================
-- 신규 회원가입 → 관리자(본인) 전용 알림
-- 고객(가입자)에게는 어떤 알림도 가지 않습니다.
-- SQL 실행 불필요. Render 환경변수 + Supabase 웹훅만 설정하면 됩니다.
-- ============================================================
--
-- ── 1) Render 환경변수 (공통) ──
--   SIGNUP_WEBHOOK_SECRET = 임의의 긴 문자열
--
-- ── 2-A) Telegram (폰 알림 추천) ──
--   1. @BotFather 에서 봇 생성 → 토큰 복사
--   2. 봇에게 아무 메시지 보낸 뒤 chat_id 확인:
--      https://api.telegram.org/bot<TOKEN>/getUpdates
--   3. Render:
--      SIGNUP_NOTIFY_TELEGRAM_BOT_TOKEN = 봇 토큰
--      SIGNUP_NOTIFY_TELEGRAM_CHAT_ID   = 본인 chat_id (숫자)
--
-- ── 2-B) Email (본인 메일로만) ──
--   SIGNUP_NOTIFY_EMAIL_TO = 본인 이메일 (쉼표로 여러 개 가능)
--
--   방법 1 — Gmail SMTP:
--      SMTP_HOST=smtp.gmail.com
--      SMTP_PORT=587
--      SMTP_USER=본인@gmail.com
--      SMTP_PASS=Gmail 앱 비밀번호 (2단계인증 후 생성)
--      SIGNUP_NOTIFY_EMAIL_FROM=팔자연구소 <본인@gmail.com>
--
--   방법 2 — Resend (resend.com):
--      RESEND_API_KEY=re_...
--      SIGNUP_NOTIFY_EMAIL_FROM=팔자연구소 <verified@도메인>
--
-- ── 3) Supabase Database Webhook ──
--   Dashboard → Database → Webhooks → Create hook
--   Table   : profiles
--   Events  : INSERT
--   URL     : https://8code.kr/api/webhooks/signup?secret=<SIGNUP_WEBHOOK_SECRET>
--   Method  : POST
--   Headers :
--     Content-Type: application/json
--   ※ Supabase Database Webhook은 커스텀 Authorization/x-signup-secret 헤더가
--     서버까지 전달되지 않는 경우가 많아 URL 쿼리 secret 방식을 사용합니다.
--
-- ── 4) 테스트 ──
--   테스트 계정으로 가입 → Telegram 또는 본인 메일 수신 확인
--
-- profiles 는 auth.users 가입 시 handle_new_user 트리거로 자동 생성됩니다.
-- 이메일·구글·카카오·네이버 가입 모두 동일하게 관리자에게만 알림이 갑니다.
