/**
 * Generate lib/counselor-ai-prompts.js — prompt bodies stored via JSON.stringify.
 * node scripts/_gen_counselor_ai_prompts.js
 */
'use strict';

const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

function extractTpl(src, assignNeedle) {
  const idx = src.indexOf(assignNeedle);
  if (idx < 0) throw new Error('missing: ' + assignNeedle.slice(0, 80));
  const eq = src.indexOf('=', idx);
  const open = src.indexOf('`', eq);
  let end = open + 1;
  while (end < src.length) {
    if (src[end] === '\\') {
      end += 2;
      continue;
    }
    if (src[end] === '`') break;
    end += 1;
  }
  return src.slice(open + 1, end);
}

function buildSystemVariants(raw) {
  const marker = "${readingDepth === 'integrated' ? '";
  let card = raw;
  let integ = raw;
  while (integ.includes(marker)) {
    const i = integ.indexOf(marker);
    const startContent = i + marker.length;
    const close = integ.indexOf("' : ''}", startContent);
    if (close < 0) throw new Error('unclosed readingDepth ternary');
    const yes = integ.slice(startContent, close);
    integ = integ.slice(0, i) + yes + integ.slice(close + "' : ''}".length);
    const i2 = card.indexOf(marker);
    const start2 = i2 + marker.length;
    const close2 = card.indexOf("' : ''}", start2);
    card = card.slice(0, i2) + card.slice(close2 + "' : ''}".length);
  }
  if (card.includes('${') || integ.includes('${')) {
    throw new Error('leftover template expr');
  }
  return { card, integ };
}

const reading = fs.readFileSync(path.join(root, 'public/counselor-reading.html'), 'utf8');
const leno = fs.readFileSync(path.join(root, 'public/counselor-lenormand.html'), 'utf8');
const iching = fs.readFileSync(path.join(root, 'public/counselor-iching.html'), 'utf8');
const kirke = fs.readFileSync(path.join(root, 'public/counselor-kirke.html'), 'utf8');

const systems = buildSystemVariants(extractTpl(reading, 'const systemBlock ='));
const integrationRule = extractTpl(reading, 'integratedDirective =');

const spreadKeys = ['choice_ab', 'love9', 'seven', 'horseshoe', 'love', 'choice', 'block'];
const spreadRules = {};
for (const key of spreadKeys) {
  const idx = reading.indexOf("spreadRuleKey === '" + key + "'");
  if (idx < 0) throw new Error('no key ' + key);
  spreadRules[key] = extractTpl(reading.slice(idx), 'spreadRuleDirective =');
}

const lengthBudget = extractTpl(reading, 'lengthBudgetDirective =');
const lenormandSystem = extractTpl(leno, 'const systemBlock =');
const ichingSystem = extractTpl(iching, 'const systemBlock =');
const ichingChoice = extractTpl(iching, "mode === 'choice' ? ");
const kirkeSystem = extractTpl(kirke, 'const systemBlock =');

const prompts = {
  SYSTEM_CARD: systems.card,
  SYSTEM_INTEGRATED: systems.integ + integrationRule,
  SPREAD_RULES: spreadRules,
  LENGTH_BUDGET: lengthBudget,
  LENORMAND_SYSTEM: lenormandSystem,
  ICHING_SYSTEM: ichingSystem,
  ICHING_CHOICE: ichingChoice,
  KIRKE_SYSTEM: kirkeSystem,
};

const logic = fs.readFileSync(path.join(__dirname, '_counselor_ai_prompts_logic.js'), 'utf8');
const out =
  "'use strict';\n" +
  '/** Auto-generated by scripts/_gen_counselor_ai_prompts.js — do not hand-edit prompt bodies. */\n' +
  'const PROMPTS = ' +
  JSON.stringify(prompts) +
  ';\n' +
  logic;

const outPath = path.join(root, 'lib/counselor-ai-prompts.js');
fs.writeFileSync(outPath, out);
console.log('wrote', outPath, out.length);

const mod = require(outPath);
const sample = mod.buildCounselorCachedMessages('counselor_session_basic', {
  displayName: '테스트',
  question: '오늘 흐름은?',
  topicLabel: '일반',
  mode: 'basic',
  readingDepth: 'card',
  spreadId: 'basic_one',
  cards: [{ pos: '현재', num: 0, name: '바보', rev: false, keywords: '시작' }],
});
const text = sample[0].content;
console.log('ok', text.includes('<core_directives>'), 'ctx', text.indexOf('\n\n<context>\n'));
